total_bases: 1000  # total bases to simulate across all isolates

samples:
  isolate_A:
    R1: mockA_R1.fastq.gz
    R2: mockA_R2.fastq.gz
    abundance: 0.7
  isolate_B:
    R1: mockB_R1.fastq.gz
    R2: mockB_R2.fastq.gz
    abundance: 0.3